name: Release Workflow

permissions:
  contents: write # Grants write access to repository contents, including releases

on:
  push:
    tags:
      - 'v*' # Triggers when a new tag starting with 'v' is pushed

jobs:
  build-and-release:
    runs-on: windows-latest # Or a matrix of OSs

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: '17.14.36310.24'

      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build Solution
        run: MSBuild.exe EyesOfficeTesterCli.sln /p:Configuration=Release /p:Platform="Any CPU"
        
      - name: Create Zip Archive
        shell: pwsh # Use PowerShell for cross-platform scripting
        run: |
          if ($env:RUNNER_OS -eq "Windows") {
            7z a EyesOfficeTesterCli.zip ./EyesOfficeTesterCli/bin/Release/net8.0-windows/* # Adjust path as needed
          } else {
            zip -r EyesOfficeTesterCli.zip ./EyesOfficeTesterCli/bin/Release/net8.0-windows # Adjust path as needed
          }
          
      - name: Rename Zip file
        shell: pwsh
        run: Move-Item -Path EyesOfficeTesterCli.zip -Destination EyesOfficeTesterCli-${{ github.ref_name }}.zip

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: EyesOfficeTesterCli-${{ github.ref_name }}.zip # Path to your built artifact
          asset_name: EyesOfficeTesterCli-${{ github.ref_name }}.zip # Name of the asset in the release
          asset_content_type: application/zip